const API_KEY = import.meta.env.VITE_GEMINI_API_KEY;
const MODEL_NAME = import.meta.env.VITE_GEMINI_MODEL || 'gemini-2.5-flash';
const API_URL = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL_NAME}:generateContent`;

/**
 * Generates a comprehensive nutrition plan using the Gemini API.
 * 
 * @param {Object} profileData - The detailed user profile collected from registration.
 * @returns {Promise<Object>} The parsed 20-point JSON report generated by Gemini.
 * @throws {Error} If the API key is missing, network fails, or JSON parsing fails.
 */
export const generateNutritionPlan = async (profileData) => {
  if (!API_KEY || API_KEY === 'your_api_key_here') {
    throw new Error('Gemini API key is missing. Please set VITE_GEMINI_API_KEY in your .env file.');
  }

  const prompt = `
    Act as a world-class nutritionist, dietician, fitness coach, and preventive healthcare advisor.
    Generate a highly personalized, comprehensive health and nutrition report based on the following detailed user profile.
    
    PERSONAL DETAILS:
    Name: ${profileData.fullName}
    Age: ${profileData.age}
    Gender: ${profileData.gender}
    Height: ${profileData.height} cm
    Weight: ${profileData.weight} kg
    Country: ${profileData.country}
    Occupation: ${profileData.occupation}
    
    LIFESTYLE INFORMATION:
    Activity Level: ${profileData.activityLevel}
    Average Daily Steps: ${profileData.dailySteps}
    Sleep Duration: ${profileData.sleepDuration} hours
    Stress Level: ${profileData.stressLevel}
    Daily Water Intake: ${profileData.waterIntake}
    Smoking Status: ${profileData.smokingStatus}
    Alcohol Consumption: ${profileData.alcoholConsumption}
    
    FOOD HABITS:
    Dietary Preference: ${profileData.dietaryPreference}
    Favorite Foods: ${profileData.favoriteFoods}
    Foods Disliked: ${profileData.dislikedFoods}
    Food Allergies: ${profileData.foodAllergies || 'None'}
    Lactose Intolerance: ${profileData.lactoseIntolerance ? 'Yes' : 'No'}
    Gluten Sensitivity: ${profileData.glutenSensitivity ? 'Yes' : 'No'}
    Meals Per Day: ${profileData.mealsPerDay}
    Fast Food Frequency: ${profileData.fastFoodFrequency}
    Daily Fruit Intake: ${profileData.fruitIntake}
    Daily Vegetable Intake: ${profileData.vegIntake}
    
    HEALTH INFORMATION:
    Existing Medical Conditions: ${profileData.medicalConditions || 'None'}
    Diabetes Status: ${profileData.diabetesStatus}
    Blood Pressure Status: ${profileData.bloodPressureStatus}
    Cholesterol Status: ${profileData.cholesterolStatus}
    Current Medications: ${profileData.medications || 'None'}
    Family Medical History: ${profileData.familyHistory || 'None'}
    Recent Health Concerns: ${profileData.recentConcerns || 'None'}
    
    FITNESS GOALS:
    Primary Goal: ${profileData.primaryGoal}
    Target Weight: ${profileData.targetWeight} kg
    Target Timeline: ${profileData.targetTimeline}
    Workout Frequency: ${profileData.workoutFrequency}
    Preferred Exercise Types: ${profileData.preferredExercises}

    CRITICAL INSTRUCTION:
    Provide the response strictly in JSON format. The response MUST be uniquely generated based on the complex interplay of this user's specific health conditions, goals, and lifestyle. Do not use generic templates.
    Generate a highly detailed 10-day nutrition plan, where every day has different foods.
    The response should be extremely detailed and comprehensive (at least 1500 words total content).
    The JSON must contain the exact following structure:
    {
      "nutritionAssessment": "Detailed summary of their current nutritional state based on profile.",
      "dailyCalorieTarget": "Exact calorie number (e.g., '2100 kcal').",
      "dailyProteinRequirement": "Exact grams (e.g., '140g').",
      "dailyCarbohydrateRecommendation": "Exact grams (e.g., '220g').",
      "dailyFatRecommendation": "Exact grams (e.g., '65g').",
      "tenDayPlan": [
        {
          "day": 1,
          "breakfast": ["Food Item 1", "Food Item 2", "Food Item 3"],
          "lunch": ["Food Item 1", "Food Item 2", "Food Item 3"],
          "dinner": ["Food Item 1", "Food Item 2", "Food Item 3"],
          "snacks": ["Food Item 1", "Food Item 2"],
          "waterIntake": "Exact liters (e.g. '3.5 Litres')"
        }
        // ... generate exactly 10 days, completely unique
      ],
      "foodsToPrioritize": "List of specific foods they should eat more of.",
      "foodsToAvoid": "List of specific foods to avoid based on their health conditions and allergies.",
      "nutritionalDeficienciesThatMayOccur": "Analysis of potential deficiencies.",
      "lifestyleImprovementRecommendations": "Advice on stress, smoking, alcohol, etc.",
      "sleepImprovementSuggestions": "Specific actionable sleep advice.",
      "fitnessRecommendations": "Specific workout routine advice.",
      "longTermHealthStrategy": "Sustainable advice for long-term health and disease prevention.",
      "potentialHealthRisks": "Warnings based on medical history and habits.",
      "personalizedMotivationalMessage": "A strong motivational message tailored to their specific goal."
    }
  `;

  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 30000); // 30 second timeout

    const response = await fetch(`${API_URL}?key=${API_KEY}`, {
      method: 'POST',
      signal: controller.signal,
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [{ text: prompt }]
          }
        ],
        generationConfig: {
          responseMimeType: 'application/json',
          temperature: 0.8,
        }
      })
    });

    clearTimeout(timeoutId);

    if (!response.ok) {
      const errorData = await response.json();
      
      // Auto-detect models if there's a model not found error
      if (errorData.error?.message?.includes('is not found') || errorData.error?.message?.includes('not supported')) {
        try {
          const modelsRes = await fetch(`https://generativelanguage.googleapis.com/v1beta/models?key=${API_KEY}`);
          if (modelsRes.ok) {
            const modelsData = await modelsRes.json();
            const availableModels = modelsData.models
              .filter(m => m.supportedGenerationMethods && m.supportedGenerationMethods.includes('generateContent'))
              .map(m => m.name.replace('models/', ''))
              .join(', ');
            throw new Error(`API KEY DIAGNOSTICS: Your key supports these models: [${availableModels || 'NONE'}]. Please set VITE_GEMINI_MODEL in your .env to one of these.`);
          } else {
            throw new Error(`API KEY DIAGNOSTICS FAILED: Could not fetch models list. Status: ${modelsRes.status}`);
          }
        } catch (fetchError) {
          throw new Error(fetchError.message || 'Failed to run diagnostics.');
        }
      }
      
      throw new Error(errorData.error?.message || 'Failed to fetch from Gemini API');
    }

    const data = await response.json();
    let resultText = data.candidates[0].content.parts[0].text;
    
    // Critical Bug Fix: Gemini sometimes wraps JSON in Markdown formatting (```json ... ```)
    resultText = resultText.replace(/```json/g, '').replace(/```/g, '').trim();
    
    try {
      const parsedData = JSON.parse(resultText);
      // Add timestamp to the report
      parsedData.id = Date.now().toString();
      parsedData.timestamp = new Date().toISOString();
      return parsedData;
    } catch (parseError) {
      throw new Error('Failed to parse the Gemini response format.');
    }
  } catch (error) {
    console.error('Gemini Service Error:', error);
    if (error.name === 'AbortError') {
      throw new Error('The request to Gemini AI timed out. Please check your internet connection or try using a VPN if the API is restricted in your region.');
    }
    throw error;
  }
};
